import {
  Briefcase,
  Heart,
  DollarSign,
  Book,
  Users,
  Sprout,
  LayoutDashboard,
  CheckSquare,
  Calendar,
  Settings,
  Moon,
  Sun,
  Plus,
  Edit,
  Trash2,
  X,
  Menu,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  CheckCircle,
  Check,
  Smile,
  Target,
  Palette,
  Info,
  FileText,
  Mail,
  Database,
  Bell,
  Zap,
  Download,
  Upload,
  Search,
  User,
  LogOut,
  Github,
  Twitter,
  MessageSquare,
  Mic,
  Star,
  TrendingUp,
  TrendingDown,
  Trophy,
  AlertTriangle,
  BarChart3,
  Lightbulb,
  Sparkles,
  Bug,
  Circle,
  Sunrise,
  Brain,
  Flame,
} from 'lucide-react';
import type { Task } from '../types/task';

export type IconType = typeof LayoutDashboard;

export const getCategoryIcon = (category: Task['category']): IconType => {
  const icons: Record<Task['category'], IconType> = {
    work: Briefcase,
    health: Heart,
    finance: DollarSign,
    learning: Book,
    relationships: Users,
    'personal-growth': Sprout,
  };
  return icons[category];
};

export const getCategoryColor = (category: Task['category']): string => {
  const colors: Record<Task['category'], string> = {
    work: 'bg-blue-100 text-blue-600',
    health: 'bg-red-100 text-red-600',
    finance: 'bg-green-100 text-green-600',
    learning: 'bg-purple-100 text-purple-600',
    relationships: 'bg-pink-100 text-pink-600',
    'personal-growth': 'bg-emerald-100 text-emerald-600',
  };
  return colors[category];
};

export const Icons = {
  Dashboard: LayoutDashboard,
  Tasks: CheckSquare,
  CheckSquare,
  Calendar,
  CheckIn: Smile,
  Settings,
  Moon,
  Sun,
  Plus,
  Edit,
  Delete: Trash2,
  Trash2,
  Close: X,
  Menu,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Error: AlertCircle,
  Success: CheckCircle,
  Check,
  CheckMark: Check,
  Logo: Sprout,
  Target,
  CheckCircle,
  Palette,
  Info,
  FileText,
  Mail,
  Database,
  Bell,
  Zap,
  Download,
  Upload,
  Search,
  Heart,
  User,
  LogOut,
  Github,
  Twitter,
  MessageSquare,
  Mic,
  Star,
  TrendingUp,
  TrendingDown,
  Trophy,
  Alert: AlertTriangle,
  AlertTriangle,
  BarChart: BarChart3,
  Lightbulb,
  Sparkles,
  Bug,
  Circle,
  Dot: Circle,
  Sunrise,
  Brain,
  Briefcase,
  DollarSign,
  Book,
  Users,
  Sprout,
  Flame,
};
